export const GET_THUMB = 'GET_THUMB';
export const GET_THUMB_SUCCESS = 'GET_THUMB_SUCCESS';
export const GET_THUMB_FAILED = 'GET_THUMB_FAILED';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILED = 'GET_POST_FAILED';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const GET_ALL_TAGS = 'GET_ALL_TAGS';
export const GET_ALL_TAGS_SUCCESS = 'GET_ALL_TAGS_SUCCESS';
export const GET_ALL_TAGS_FAILED = 'GET_ALL_TAGS_FAILED';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';

export const GET_POPULAR_ARTICLE = 'GET_POPULAR_ARTICLE';
export const GET_POPULAR_ARTICLE_SUCCESS = 'GET_POPULAR_ARTICLE_SUCCESS';
export const GET_POPULAR_ARTICLE_FAILED = 'GET_POPULAR_ARTICLE_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const FILTER_POST_BY_TAGNAME_REQUEST = 'FILTER_POST_BY_TAGNAME_REQUEST';
export const FILTER_POST_BY_TAGNAME_SUCCESS = 'FILTER_POST_BY_TAGNAME_SUCCESS';
export const FILTER_POST_BY_TAGNAME_FAILURE = 'FILTER_POST_BY_TAGNAME_FAILURE';

export const FILTER_POST_BY_CATEGORY_REQUEST =
  'FILTER_POST_BY_CATEGORY_REQUEST';
export const FILTER_POST_BY_CATEGORY_SUCCESS =
  'FILTER_POST_BY_CATEGORY_SUCCESS';
export const FILTER_POST_BY_CATEGORY_FAILURE =
  'FILTER_POST_BY_CATEGORY_FAILURE';

export const SEARCH_POST_NAME_REQUEST = 'SEARCH_POST_NAME_REQUEST';
export const SEARCH_POST_NAME_SUCCESS = 'SEARCH_POST_NAME_SUCCESS';
export const SEARCH_POST_NAME_FAILURE = 'SEARCH_POST_NAME_FAILURE';

export const GET_ALL_COMMENTS_REQUEST = 'GET_ALL_COMMENTS_REQUEST';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAILURE = 'GET_ALL_COMMENTS_FAILURE';
